name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Ubuntu VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build  # Adjust this if you don't have a build step

      - name: Deploy via SSH to Ubuntu VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /opt/actions
            git pull origin main
            npm install
            pm2 restart app || pm2 start npm --name "app" -- start
