name: Deploy to Ubuntu VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: tech
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/actions
            git pull origin main
            npm install
            pm2 restart app || pm2 start app.js --name app

